// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKbZddmJtr2K6rIS7SXKJ71NcB6mRKFzE',
    appId: '1:453183372061:web:142d400acf1839b3633ff4',
    messagingSenderId: '453183372061',
    projectId: 'bhanubpsn-d7722',
    authDomain: 'bhanubpsn-d7722.firebaseapp.com',
    storageBucket: 'bhanubpsn-d7722.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYn8GocI1lYsgwZL5yWXg2kOx9LvDQESs',
    appId: '1:453183372061:android:ba631cd9971fac6f633ff4',
    messagingSenderId: '453183372061',
    projectId: 'bhanubpsn-d7722',
    storageBucket: 'bhanubpsn-d7722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxbTH9b43RCMtGt4tbhhnRI4Re1MxPaU',
    appId: '1:453183372061:ios:60dcb49c82f715c7633ff4',
    messagingSenderId: '453183372061',
    projectId: 'bhanubpsn-d7722',
    storageBucket: 'bhanubpsn-d7722.appspot.com',
    iosClientId: '453183372061-9ksk3p3i2pqadn7h9spar55u0pb2fm5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpsn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuxbTH9b43RCMtGt4tbhhnRI4Re1MxPaU',
    appId: '1:453183372061:ios:60dcb49c82f715c7633ff4',
    messagingSenderId: '453183372061',
    projectId: 'bhanubpsn-d7722',
    storageBucket: 'bhanubpsn-d7722.appspot.com',
    iosClientId: '453183372061-9ksk3p3i2pqadn7h9spar55u0pb2fm5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpsn',
  );
}
